import React from 'react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';

const DEGREES = [
  'High School Diploma',
  'Associate Degree',
  'Bachelor of Arts (BA)',
  'Bachelor of Science (BS)',
  'Bachelor of Business Administration (BBA)',
  'Bachelor of Engineering (BE)',
  'Bachelor of Technology (BTech)',
  'Master of Arts (MA)',
  'Master of Science (MS)',
  'Master of Business Administration (MBA)',
  'Master of Engineering (ME)',
  'Master of Technology (MTech)',
  'Doctor of Philosophy (PhD)',
  'Juris Doctor (JD)',
  'Doctor of Medicine (MD)',
  'Doctor of Education (EdD)',
  'Certificate',
  'Diploma',
  'Other'
];

const MAJORS = [
  'Computer Science',
  'Information Technology',
  'Software Engineering',
  'Data Science',
  'Artificial Intelligence',
  'Business Administration',
  'Finance',
  'Accounting',
  'Marketing',
  'Economics',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Psychology',
  'Sociology',
  'Political Science',
  'English',
  'Communications',
  'Nursing',
  'Biology',
  'Chemistry',
  'Physics',
  'Mathematics',
  'Statistics',
  'Graphic Design',
  'Fine Arts',
  'Education',
  'Law',
  'Medicine',
  'Other'
];

const UNIVERSITIES = [
  'Aalto University',
  'Aarhus University',
  'Abilene Christian University',
  'Academy of Art University',
  'Adams State University',
  'Adelphi University',
  'Adler University',
  'Adrian College',
  'Agnes Scott College',
  'Air Force Institute of Technology',
  'Aix-Marseille University',
  'Alabama A&M University',
  'Alabama State University',
  'Alaska Pacific University',
  'Albany College of Pharmacy',
  'Albany State University',
  'Albertus Magnus College',
  'Albion College',
  'Albright College',
  'Alcorn State University',
  'Alderson Broaddus University',
  'Alfred University',
  'Allegheny College',
  'Allen University',
  'Alliant International University',
  'Alma College',
  'Alvernia University',
  'Alverno College',
  'Amberton University',
  'American International College',
  'American Jewish University',
  'American University',
  'American University in Cairo',
  'American University of Beirut',
  'Amherst College',
  'Anderson University',
  'Andrews University',
  'Angelo State University',
  'Anna University',
  'Antioch University',
  'Appalachian State University',
  'Aquinas College',
  'Arcadia University',
  'Arizona Christian University',
  'Arizona State University',
  'Arkansas Baptist College',
  'Arkansas State University',
  'Arkansas Tech University',
  'Armstrong State University',
  'Art Center College of Design',
  'Asbury University',
  'Ashford University',
  'Ashland University',
  'Assumption College',
  'Athens State University',
  'Atlantic University',
  'Auburn University',
  'Auburn University at Montgomery',
  'Augsburg University',
  'Augusta University',
  'Augustana College',
  'Augustana University',
  'Aurora University',
  'Austin College',
  'Austin Peay State University',
  'Ave Maria University',
  'Averett University',
  'Avila University',
  'Azusa Pacific University',
  'Babson College',
  'Baker College',
  'Baker University',
  'Baldwin Wallace University',
  'Australian National University',
  'Autonomous University of Madrid',
  'Ball State University',
  'Banaras Hindu University',
  'Baptist Bible College',
  'Barclay College',
  'Bard College',
  'Barnard College',
  'Barry University',
  'Barton College',
  'Bastyr University',
  'Bates College',
  'Bay Path University',
  'Baylor University',
  'Beacon College',
  'Becker College',
  'Belhaven University',
  'Bellarmine University',
  'Bellevue University',
  'Beihang University',
  'Belmont Abbey College',
  'Belmont University',
  'Beloit College',
  'Bemidji State University',
  'Benedict College',
  'Benedictine College',
  'Benedictine University',
  'Bennett College',
  'Bennington College',
  'Bentley University',
  'Berea College',
  'Berkeley College',
  'Berklee College of Music',
  'Berry College',
  'Bethany College',
  'Bethel College',
  'Bethel University',
  'Bethune-Cookman University',
  'Binghamton University',
  'Biola University',
  'Birmingham-Southern College',
  'Black Hills State University',
  'Blackburn College',
  'Bloomfield College',
  'Bloomsburg University',
  'Blue Mountain College',
  'Bluefield College',
  'Bluefield State College',
  'Bluffton University',
  'Birla Institute of Technology and Science (BITS Pilani)',
  'Bob Jones University',
  'Boise State University',
  'Boston College',
  'Boston University',
  'Bowdoin College',
  'Bowie State University',
  'Bowling Green State University',
  'Bradley University',
  'Brandeis University',
  'Brandman University',
  'Brenau University',
  'Brescia University',
  'Brevard College',
  'Briar Cliff University',
  'Bridgewater College',
  'Bridgewater State University',
  'Brigham Young University',
  'Brigham Young University-Hawaii',
  'Brigham Young University-Idaho',
  'Brooklyn College',
  'Brown University',
  'Bryan College',
  'Bryant University',
  'Bryn Athyn College',
  'Bryn Mawr College',
  'Bucknell University',
  'Buena Vista University',
  'Buffalo State College',
  'Butler University',
  'Cabrini University',
  'Cairn University',
  'Cairo University',
  'Caldwell University',
  'California Baptist University',
  'California College of the Arts',
  'California Institute of Integral Studies',
  'California Institute of Technology (Caltech)',
  'California Institute of the Arts',
  'California Lutheran University',
  'California Maritime Academy',
  'California Polytechnic State University',
  'California State Polytechnic University, Pomona',
  'California State University, Bakersfield',
  'California State University, Channel Islands',
  'California State University, Chico',
  'California State University, Dominguez Hills',
  'California State University, East Bay',
  'California State University, Fresno',
  'California State University, Fullerton',
  'California State University, Long Beach',
  'California State University, Los Angeles',
  'California State University, Monterey Bay',
  'California State University, Northridge',
  'California State University, Sacramento',
  'California State University, San Bernardino',
  'California State University, San Marcos',
  'California State University, Stanislaus',
  'California University of Pennsylvania',
  'Calumet College of St. Joseph',
  'Calvary University',
  'Calvin College',
  'Cambridge College',
  'Cameron University',
  'Campbell University',
  'Campbellsville University',
  'Canisius College',
  'Capella University',
  'Capital University',
  'Capitol Technology University',
  'Cardinal Stritch University',
  'Carleton College',
  'Carleton University',
  'Carlow University',
  'Carnegie Mellon University',
  'Carroll College',
  'Carroll University',
  'Carson-Newman University',
  'Carthage College',
  'Case Western Reserve University',
  'Castleton University',
  'Catawba College',
  'Catholic University of America',
  'Cazenovia College',
  'Cedar Crest College',
  'Cedarville University',
  'Centenary College of Louisiana',
  'Centenary University',
  'Central Baptist College',
  'Central Christian College of Kansas',
  'Central College',
  'Central Connecticut State University',
  'Central Methodist University',
  'Central Michigan University',
  'Central Pennsylvania College',
  'Central State University',
  'Central Washington University',
  'Centre College',
  'Chadron State College',
  'Chambersburg University',
  'Chamberlain University',
  'Chaminade University',
  'Champlain College',
  'Chalmers University of Technology',
  'Chapman University',
  'Charter Oak State College',
  'Chatham University',
  'Chestnut Hill College',
  'Cheyney University',
  'Chicago State University',
  'Chinese University of Hong Kong',
  'Chowan University',
  'Christendom College',
  'Christian Brothers University',
  'Christopher Newport University',
  'Cincinnati Christian University',
  'City College of New York',
  'City University of Hong Kong',
  'City University of Seattle',
  'Claflin University',
  'Claremont Graduate University',
  'Claremont McKenna College',
  'Clarion University',
  'Clark Atlanta University',
  'Clark University',
  'Clarke University',
  'Clarkson University',
  'Clayton State University',
  'Cleary University',
  'Clemson University',
  'Cleveland Institute of Art',
  'Cleveland Institute of Music',
  'Cleveland State University',
  'Coastal Carolina University',
  'Coe College',
  'Coker College',
  'Colby College',
  'Colby-Sawyer College',
  'Colgate University',
  'College of Charleston',
  'College of Mount Saint Vincent',
  'College of New Rochelle',
  'College of Saint Benedict',
  'College of Saint Elizabeth',
  'College of Saint Mary',
  'College of Saint Rose',
  'College of the Atlantic',
  'College of the Holy Cross',
  'College of the Ozarks',
  'College of William & Mary',
  'Colorado Christian University',
  'Colorado College',
  'Colorado Mesa University',
  'Colorado Mountain College',
  'Colorado School of Mines',
  'Colorado State University',
  'Colorado State University-Pueblo',
  'Colorado Technical University',
  'Columbia College',
  'Columbia College Chicago',
  'Columbia International University',
  'Columbia University',
  'Columbus State University',
  'Concord University',
  'Concordia College',
  'Concordia University',
  'Concordia University Chicago',
  'Concordia University Irvine',
  'Concordia University Texas',
  'Concordia University Wisconsin',
  'Connecticut College',
  'Converse College',
  'Cooper Union',
  'Coppin State University',
  'Corban University',
  'Cornell College',
  'Complutense University of Madrid',
  'Cornell University',
  'Creighton University',
  'Daemen College',
  'Dakota State University',
  'Dakota Wesleyan University',
  'Dallas Baptist University',
  'Dalton State College',
  'Dalhousie University',
  'Daniel Webster College',
  'Dartmouth College',
  'Davenport University',
  'Davidson College',
  'Davis & Elkins College',
  'Defiance College',
  'Delaware State University',
  'Delaware Valley University',
  'Delta State University',
  'Denison University',
  'Delft University of Technology',
  'Delhi University',
  'DePaul University',
  'DePauw University',
  'DeSales University',
  'Dickinson College',
  'Dickinson State University',
  'Dillard University',
  'Dixie State University',
  'Doane University',
  'Dominican College',
  'Dominican University',
  'Dominican University of California',
  'Dordt College',
  'Drake University',
  'Drew University',
  'Drexel University',
  'Drury University',
  'Duke University',
  'Duquesne University',
  'D'Youville College',
  'Earlham College',
  'Durham University',
  'East Carolina University',
  'East Central University',
  'East Stroudsburg University',
  'East Tennessee State University',
  'East Texas Baptist University',
  'Eastern Connecticut State University',
  'Eastern Illinois University',
  'Eastern Kentucky University',
  'Eastern Mennonite University',
  'Eastern Michigan University',
  'Eastern Nazarene College',
  'Eastern New Mexico University',
  'Eastern Oregon University',
  'Eastern University',
  'Eastern Washington University',
  'Eckerd College',
  'Edgewood College',
  'Edinboro University',
  'Elizabeth City State University',
  'Elizabethtown College',
  'Elmhurst College',
  'Elmira College',
  'Elon University',
  'Embry-Riddle Aeronautical University',
  'École Normale Supérieure',
  'École Polytechnique',
  'Eindhoven University of Technology',
  'Emerson College',
  'Emmanuel College',
  'Emmaus Bible College',
  'Emory & Henry College',
  'Emory University',
  'Emporia State University',
  'Endicott College',
  'EPFL (École Polytechnique Fédérale de Lausanne)',
  'Erskine College',
  'Eureka College',
  'Evangel University',
  'Evergreen State College',
  'Erasmus University Rotterdam',
  'ETH Zurich',
  'Fairfield University',
  'Fairleigh Dickinson University',
  'Fairmont State University',
  'Fashion Institute of Technology',
  'Faulkner University',
  'Fayetteville State University',
  'Federal University of Rio de Janeiro',
  'Felician University',
  'Ferris State University',
  'Ferrum College',
  'Fielding Graduate University',
  'Finlandia University',
  'Fisher College',
  'Fisk University',
  'Fitchburg State University',
  'Flagler College',
  'Florida Agricultural and Mechanical University',
  'Florida Atlantic University',
  'Florida College',
  'Florida Gulf Coast University',
  'Florida Institute of Technology',
  'Florida International University',
  'Florida Memorial University',
  'Florida Southern College',
  'Florida State University',
  'Fontbonne University',
  'Fordham University',
  'Fort Hays State University',
  'Fort Lewis College',
  'Fort Valley State University',
  'Framingham State University',
  'Francis Marion University',
  'Franciscan University of Steubenville',
  'Franklin & Marshall College',
  'Franklin College',
  'Franklin Pierce University',
  'Franklin University',
  'Franklin W. Olin College of Engineering',
  'Freed-Hardeman University',
  'Fresno Pacific University',
  'Friends University',
  'Frostburg State University',
  'Full Sail University',
  'Furman University',
  'Gallaudet University',
  'Gannon University',
  'Gardner-Webb University',
  'Free University of Berlin',
  'Fudan University',
  'Geneva College',
  'George Fox University',
  'George Mason University',
  'George Washington University',
  'Georgetown College',
  'Georgetown University',
  'Georgia College & State University',
  'Georgia Gwinnett College',
  'Georgia Institute of Technology',
  'Georgia Regents University',
  'Georgia Southern University',
  'Georgia Southwestern State University',
  'Georgia State University',
  'Georgian Court University',
  'Gettysburg College',
  'Ghent University',
  'Glenville State College',
  'Goddard College',
  'Golden Gate University',
  'Goldey-Beacom College',
  'Gonzaga University',
  'Goodwin College',
  'Gordon College',
  'Goshen College',
  'Goucher College',
  'Governors State University',
  'Grace College',
  'Graceland University',
  'Grambling State University',
  'Grand Canyon University',
  'Grand Valley State University',
  'Grand View University',
  'Granite State College',
  'Grantham University',
  'Green Mountain College',
  'Greensboro College',
  'Greenville College',
  'Grinnell College',
  'Grove City College',
  'Guilford College',
  'Gustavus Adolphus College',
  'Gwynedd Mercy University',
  'Grenoble Alpes University',
  'Hamilton College',
  'Hamline University',
  'Hampden-Sydney College',
  'Hampshire College',
  'Hampton University',
  'Hannibal-LaGrange University',
  'Hanover College',
  'Hanyang University',
  'Harding University',
  'Hardin-Simmons University',
  'Harris-Stowe State University',
  'Hartwick College',
  'Harbin Institute of Technology',
  'Harvard University',
  'Harvey Mudd College',
  'Haskell Indian Nations University',
  'Hastings College',
  'Haverford College',
  'Hawaii Pacific University',
  'Heidelberg University (Ohio)',
  'Henderson State University',
  'Hendrix College',
  'Heritage University',
  'High Point University',
  'Hilbert College',
  'Hillsdale College',
  'Hiram College',
  'Hobart and William Smith Colleges',
  'HEC Paris',
  'Hebrew University of Jerusalem',
  'Heidelberg University',
  'Hokkaido University',
  'Hong Kong Polytechnic University',
  'Hong Kong University of Science and Technology',
  'Howard Payne University',
  'Howard University',
  'Humboldt State University',
  'Humboldt University of Berlin',
  'Humphreys College',
  'Hunter College',
  'Huntingdon College',
  'Huntington University',
  'Husson University',
  'Huston-Tillotson University',
  'IE Business School',
  'Illinois Institute of Technology',
  'Illinois State University',
  'Imperial College London',
  'Indiana Institute of Technology',
  'Indiana State University',
  'Indiana University Bloomington',
  'Indiana University East',
  'Indiana University Kokomo',
  'Indiana University Northwest',
  'Indiana University of Pennsylvania',
  'Indiana University South Bend',
  'Indiana University Southeast',
  'Indiana University-Purdue University Fort Wayne',
  'Indiana University-Purdue University Indianapolis',
  'Indiana Wesleyan University',
  'INSEAD',
  'Iona College',
  'Iowa State University',
  'Iowa Wesleyan University',
  'Ithaca College',
  'Jackson State University',
  'Jacksonville State University',
  'Jacksonville University',
  'Jadavpur University',
  'James Madison University',
  'Jamestown University',
  'Jarvis Christian College',
  'Jawaharlal Nehru University',
  'John Brown University',
  'John Carroll University',
  'Johns Hopkins University',
  'Johnson & Wales University',
  'Johnson C. Smith University',
  'Johnson State College',
  'Johnson University',
  'Judson College',
  'Judson University',
  'Juniata College',
  'KAIST',
  'Kalamazoo College',
  'Kansas City Art Institute',
  'Kansas State University',
  'Kansas Wesleyan University',
  'Kean University',
  'Keene State College',
  'Karlsruhe Institute of Technology',
  'Keio University',
  'Kendall College',
  'Kennesaw State University',
  'Kent State University',
  'Kentucky State University',
  'Kentucky Wesleyan College',
  'Kenyon College',
  'Kettering University',
  'Keuka College',
  'King Abdullah University of Science and Technology',
  'King University',
  'King\'s College',
  'King\'s College London',
  'Knox College',
  'Korea University',
  'KU Leuven',
  'Kyoto University',
  'Kyushu University',
  'La Roche College',
  'La Salle University',
  'La Sierra University',
  'Lafayette College',
  'LaGrange College',
  'Laguna College of Art and Design',
  'Lake Erie College',
  'Lake Forest College',
  'Lake Superior State University',
  'Lakeland College',
  'Lamar University',
  'Lancaster Bible College',
  'Lancaster University',
  'Lander University',
  'Lane College',
  'Langston University',
  'Lasell College',
  'Lawrence Technological University',
  'Lawrence University',
  'Le Moyne College',
  'Lebanon Valley College',
  'Lee University',
  'Lees-McRae College',
  'Lehigh University',
  'LeMoyne-Owen College',
  'Lenoir-Rhyne University',
  'Lesley University',
  'LeTourneau University',
  'Lewis & Clark College',
  'Lewis University',
  'Lewis-Clark State College',
  'Leiden University',
  'Liberty University',
  'London School of Economics (LSE)',
  'Long Island University',
  'Louisiana State University',
  'Louisiana State University Shreveport',
  'Louisiana Tech University',
  'Loughborough University',
  'Lourdes University',
  'Loyola Marymount University',
  'Loyola University Chicago',
  'Loyola University Maryland',
  'Loyola University New Orleans',
  'Lubbock Christian University',
  'Luther College',
  'Lycoming College',
  'Lynchburg College',
  'Lyndon State College',
  'Lynn University',
  'Lyon College',
  'Ludwig Maximilian University of Munich',
  'Lund University',
  'Macquarie University',
  'Marlboro College',
  'Marquette University',
  'Mars Hill University',
  'Marshall University',
  'Martin Luther College',
  'Martin Methodist College',
  'Martin University',
  'Mary Baldwin College',
  'Marymount California University',
  'Marymount Manhattan College',
  'Marymount University',
  'Maryville College',
  'Maryville University',
  'Marywood University',
  'Massachusetts College of Art and Design',
  'Massachusetts College of Liberal Arts',
  'Massachusetts Institute of Technology (MIT)',
  'Massachusetts Maritime Academy',
  'Mayville State University',
  'McDaniel College',
  'McHenry County College',
  'McKendree University',
  'McMurry University',
  'McNally Smith College of Music',
  'McNeese State University',
  'McPherson College',
  'McGill University',
  'McMaster University',
  'Medaille College',
  'Medgar Evers College',
  'Menlo College',
  'Mercer University',
  'Mercy College',
  'Mercyhurst University',
  'Meredith College',
  'Merrimack College',
  'Mesa State College',
  'Messiah College',
  'Methodist University',
  'Metropolitan College of New York',
  'Metropolitan State University',
  'Metropolitan State University of Denver',
  'Miami Dade College',
  'Miami University',
  'Michigan State University',
  'Michigan Technological University',
  'Mid-America Christian University',
  'Middle Georgia State University',
  'Middle Tennessee State University',
  'Middlebury College',
  'Midland University',
  'Midway College',
  'Midwestern State University',
  'Miles College',
  'Millersville University',
  'Milligan College',
  'Millikin University',
  'Mills College',
  'Millsaps College',
  'Milwaukee School of Engineering',
  'Minnesota State University, Mankato',
  'Minnesota State University Moorhead',
  'Minot State University',
  'Misericordia University',
  'Mississippi College',
  'Mississippi State University',
  'Mississippi University for Women',
  'Mississippi Valley State University',
  'Missouri Baptist University',
  'Missouri Southern State University',
  'Missouri State University',
  'Missouri University of Science and Technology',
  'Missouri Valley College',
  'Missouri Western State University',
  'Mitchell College',
  'Monash University',
  'Montana State University',
  'Monterrey Institute of Technology',
  'Montreat College',
  'Montserrat College of Art',
  'Moody Bible Institute',
  'Moravian College',
  'Morehead State University',
  'Morehouse College',
  'Morgan State University',
  'Morningside College',
  'Morris College',
  'Mount Aloysius College',
  'Mount Holyoke College',
  'Mount Ida College',
  'Mount Mary University',
  'Mount Mercy University',
  'Mount Saint Mary College',
  'Mount Saint Mary\'s University',
  'Mount St. Joseph University',
  'Mount Vernon Nazarene University',
  'Muhlenberg College',
  'Multnomah University',
  'Murray State University',
  'Muskingum University',
  'Nagoya University',
  'Nanjing University',
  'Naropa University',
  'National Defense University',
  'National Louis University',
  'Nankai University',
  'Nanyang Technological University',
  'National Autonomous University of Mexico',
  'National University',
  'National University of Singapore',
  'Nazarene Bible College',
  'Nazareth College',
  'Nebraska Methodist College',
  'Nebraska Wesleyan University',
  'Neumann University',
  'Nevada State College',
  'New College of Florida',
  'New England College',
  'New England Conservatory',
  'New England Institute of Technology',
  'New Jersey City University',
  'New Jersey Institute of Technology',
  'New Mexico Highlands University',
  'New Mexico Institute of Mining and Technology',
  'New Mexico State University',
  'New Saint Andrews College',
  'New York Institute of Technology',
  'New York University (NYU)',
  'Newberry College',
  'Newcastle University',
  'Newman University',
  'Newmont College',
  'Niagara University',
  'Nicholls State University',
  'Nichols College',
  'Norfolk State University',
  'North Carolina A&T State University',
  'North Carolina Central University',
  'North Carolina State University',
  'North Carolina Wesleyan College',
  'North Central College',
  'North Central University',
  'North Dakota State University',
  'North Georgia College & State University',
  'North Greenville University',
  'North Park University',
  'Northcentral University',
  'Northeast University',
  'Northeastern Illinois University',
  'Northeastern State University',
  'Northeastern University',
  'Northern Arizona University',
  'Northern Illinois University',
  'Northern Kentucky University',
  'Northern Michigan University',
  'Northern State University',
  'Northern Vermont University',
  'Northland College',
  'Northwest Christian University',
  'Northwest Missouri State University',
  'Northwest Nazarene University',
  'Northwest University',
  'Northwestern College',
  'Northwestern Oklahoma State University',
  'Northwestern State University',
  'Northwestern University',
  'Northwood University',
  'Norwich University',
  'Notre Dame College',
  'Notre Dame de Namur University',
  'Nova Southeastern University',
  'Oakland City University',
  'Oakland University',
  'Oakwood University',
  'Oberlin College',
  'Occidental College',
  'Oglala Lakota College',
  'Oglethorpe University',
  'Ohio Christian University',
  'Ohio Dominican University',
  'Ohio Northern University',
  'Ohio State University',
  'Ohio University',
  'Ohio Valley University',
  'Ohio Wesleyan University',
  'Oklahoma Baptist University',
  'Oklahoma Christian University',
  'Oklahoma City University',
  'Oklahoma Panhandle State University',
  'Oklahoma State University',
  'Oklahoma Wesleyan University',
  'Old Dominion University',
  'Olivet College',
  'Olivet Nazarene University',
  'Oral Roberts University',
  'Oregon Health & Science University',
  'Oregon Institute of Technology',
  'Oregon State University',
  'Otis College of Art and Design',
  'Ottawa University',
  'Otterbein University',
  'Ouachita Baptist University',
  'Our Lady of the Lake University',
  'Osaka University',
  'Pace University',
  'Pacific College',
  'Pacific Lutheran University',
  'Pacific Northwest College of Art',
  'Pacific Oaks College',
  'Pacific Union College',
  'Pacific University',
  'Paine College',
  'Palm Beach Atlantic University',
  'Park University',
  'Paul Quinn College',
  'Paul Smith\'s College',
  'Peabody Conservatory',
  'Penn State University',
  'Pennsylvania College of Technology',
  'Pepperdine University',
  'Peru State College',
  'Pfeiffer University',
  'Philadelphia University',
  'Philander Smith College',
  'Piedmont College',
  'Pikeville College',
  'Pine Manor College',
  'Pittsburg State University',
  'Pitzer College',
  'Plymouth State University',
  'Point Loma Nazarene University',
  'Point Park University',
  'Point University',
  'Politecnico di Milano',
  'Polk State College',
  'Polytechnic University of Puerto Rico',
  'Pomona College',
  'Pompeu Fabra University',
  'Pontifical Catholic University of Chile',
  'Portland State University',
  'Post University',
  'POSTECH',
  'Potomac College',
  'Prairie View A&M University',
  'Pratt Institute',
  'Presbyterian College',
  'Prescott College',
  'Princeton University',
  'Principia College',
  'Providence College',
  'Purchase College',
  'Purdue University',
  'Purdue University Calumet',
  'Purdue University North Central',
  'Qatar University',
  'Queen Mary University of London',
  'Queen\'s University',
  'Queensland University of Technology',
  'Quinnipiac University',
  'Radford University',
  'Rensselaer Polytechnic Institute',
  'Rhode Island College',
  'Rhode Island School of Design',
  'Rhodes College',
  'Rice University',
  'Rider University',
  'Ringling College of Art and Design',
  'Ripon College',
  'Rivier University',
  'Roanoke College',
  'Robert Morris University',
  'Roberts Wesleyan College',
  'RMIT University',
  'Rochester College',
  'Rochester Institute of Technology',
  'Rockford University',
  'Rockhurst University',
  'Rocky Mountain College',
  'Roger Williams University',
  'Rollins College',
  'Roosevelt University',
  'Rosalind Franklin University',
  'Rose-Hulman Institute of Technology',
  'Rosemont College',
  'Rowan University',
  'Rust College',
  'Royal Institute of Technology (KTH)',
  'Rutgers University',
  'RWTH Aachen University',
  'Sacred Heart University',
  'Sage Colleges',
  'Saginaw Valley State University',
  'Saint Ambrose University',
  'Saint Anselm College',
  'Saint Augustine\'s University',
  'Saint Francis University',
  'Saint Joseph\'s College',
  'Saint Joseph\'s University',
  'Saint Leo University',
  'Saint Louis University',
  'Saint Martin\'s University',
  'Saint Mary\'s College',
  'Saint Mary\'s College of California',
  'Saint Mary\'s University of Minnesota',
  'Saint Michael\'s College',
  'Saint Peter\'s University',
  'Saint Vincent College',
  'Saint Xavier University',
  'Salem College',
  'Salem International University',
  'Salem State University',
  'Salisbury University',
  'Salish Kootenai College',
  'Salve Regina University',
  'Sam Houston State University',
  'Samford University',
  'San Diego Christian College',
  'San Diego State University',
  'San Francisco Art Institute',
  'San Francisco Conservatory of Music',
  'San Francisco State University',
  'San Jose State University',
  'Santa Clara University',
  'Santa Fe College',
  'Sarah Lawrence College',
  'Sapienza University of Rome',
  'Sciences Po',
  'Seattle Pacific University',
  'Seattle University',
  'Seoul National University',
  'Seton Hall University',
  'Seton Hill University',
  'Sewanee: The University of the South',
  'Shawnee State University',
  'Shaw University',
  'Shenandoah University',
  'Shepherd University',
  'Shimer College',
  'Shippensburg University',
  'Shorter University',
  'Siena College',
  'Siena Heights University',
  'Sierra Nevada College',
  'Silver Lake College',
  'Simmons College',
  'Simpson College',
  'Simpson University',
  'Sitting Bull College',
  'Skidmore College',
  'Slippery Rock University',
  'Smith College',
  'Sojourner-Douglass College',
  'Soka University of America',
  'Sonoma State University',
  'Shanghai Jiao Tong University',
  'Sichuan University',
  'Simon Fraser University',
  'Singapore Management University',
  'Sorbonne University',
  'South Carolina State University',
  'South Dakota School of Mines and Technology',
  'South Dakota State University',
  'South Texas College of Law',
  'South University',
  'Southeast Missouri State University',
  'Southeastern Louisiana University',
  'Southeastern Oklahoma State University',
  'Southeastern University',
  'Southern Adventist University',
  'Southern Arkansas University',
  'Southern California Institute of Architecture',
  'Southern Connecticut State University',
  'Southern Illinois University Carbondale',
  'Southern Illinois University Edwardsville',
  'Southern Methodist University',
  'Southern Nazarene University',
  'Southern New Hampshire University',
  'Southern Oregon University',
  'Southern Polytechnic State University',
  'Southern University',
  'Southern Utah University',
  'Southern Vermont College',
  'Southern Virginia University',
  'Southern Wesleyan University',
  'Southwest Baptist University',
  'Southwest Minnesota State University',
  'Southwestern Adventist University',
  'Southwestern Assemblies of God University',
  'Southwestern Christian University',
  'Southwestern College',
  'Southwestern Oklahoma State University',
  'Southwestern University',
  'Spalding University',
  'Spelman College',
  'Spring Arbor University',
  'Spring Hill College',
  'Springfield College',
  'St. Ambrose University',
  'St. Andrews University',
  'St. Augustine College',
  'St. Bonaventure University',
  'St. Catherine University',
  'St. Cloud State University',
  'St. Edward\'s University',
  'St. Francis College',
  'St. John Fisher College',
  'St. John\'s College',
  'St. John\'s University',
  'St. Joseph\'s College',
  'St. Lawrence University',
  'St. Mary\'s College of Maryland',
  'St. Mary\'s University',
  'St. Norbert College',
  'St. Olaf College',
  'St. Paul\'s College',
  'St. Peter\'s College',
  'St. Thomas Aquinas College',
  'St. Thomas University',
  'Stanford University',
  'State University of New York',
  'State University of New York at New Paltz',
  'State University of New York at Oswego',
  'State University of New York at Plattsburgh',
  'Stellenbosch University',
  'Stephen F. Austin State University',
  'Sterling College',
  'Stetson University',
  'Stevens Institute of Technology',
  'Stevenson University',
  'Stillman College',
  'Stockholm University',
  'Stockton University',
  'Stonehill College',
  'Stony Brook University',
  'Strayer University',
  'Suffolk University',
  'Sul Ross State University',
  'Sun Yat-sen University',
  'Sungkyunkwan University',
  'Summit University',
  'SUNY Albany',
  'SUNY Buffalo',
  'SUNY Cortland',
  'SUNY Fredonia',
  'SUNY Geneseo',
  'SUNY Maritime College',
  'SUNY Oneonta',
  'SUNY Potsdam',
  'Susquehanna University',
  'Swarthmore College',
  'Sweet Briar College',
  'Syracuse University',
  'Technical University of Denmark',
  'Technical University of Munich',
  'Technion - Israel Institute of Technology',
  'Tel Aviv University',
  'Temple University',
  'Tennessee State University',
  'Tennessee Tech University',
  'Tennessee Technological University',
  'Tennessee Wesleyan College',
  'Texas A&M International University',
  'Texas A&M University',
  'Texas A&M University-Commerce',
  'Texas A&M University-Corpus Christi',
  'Texas A&M University-Kingsville',
  'Texas Christian University',
  'Texas College',
  'Texas Lutheran University',
  'Texas Southern University',
  'Texas State University',
  'Texas Tech University',
  'Texas Wesleyan University',
  'Texas Woman\'s University',
  'The American University in Dubai',
  'The Citadel',
  'The College of Idaho',
  'The College of New Jersey',
  'The College of Saint Scholastica',
  'The College of Wooster',
  'The Evergreen State College',
  'The Juilliard School',
  'The King\'s College',
  'The Master\'s College',
  'The New School',
  'The Sage Colleges',
  'The University of Tulsa',
  'Thiel College',
  'Thomas Aquinas College',
  'Thomas College',
  'Thomas Edison State College',
  'Thomas Jefferson University',
  'Thomas More College',
  'Thomas University',
  'Tianjin University',
  'Tohoku University',
  'Tokyo Institute of Technology',
  'Tougaloo College',
  'Touro College',
  'Towson University',
  'Transylvania University',
  'Trevecca Nazarene University',
  'Trine University',
  'Trinity Baptist College',
  'Trinity Christian College',
  'Trinity College',
  'Trinity International University',
  'Trinity University',
  'Trinity Washington University',
  'Troy University',
  'Truett McConnell College',
  'Truman State University',
  'Tsinghua University',
  'TU Berlin',
  'TU Dresden',
  'Tufts University',
  'Tulane University',
  'Tusculum College',
  'Tuskegee University',
  'United Arab Emirates University',
  'Université Libre de Bruxelles',
  'Université Paris-Saclay',
  'University College London (UCL)',
  'University of Aberdeen',
  'University of Adelaide',
  'Upper Iowa University',
  'Ursinus College',
  'Ursuline College',
  'Utah State University',
  'Utah Valley University',
  'Utica College',
  'University of Akron',
  'University of Alabama',
  'University of Alabama at Birmingham',
  'University of Alabama in Huntsville',
  'University of Alaska Anchorage',
  'University of Alaska Fairbanks',
  'University of Alberta',
  'University of Amsterdam',
  'University of Antwerp',
  'University of Arizona',
  'University of Arkansas',
  'University of Auckland',
  'University of Baltimore',
  'University of Barcelona',
  'University of Basel',
  'University of Bath',
  'University of Bergen',
  'University of Bern',
  'University of Birmingham',
  'University of Bologna',
  'University of Bonn',
  'University of Bristol',
  'University of British Columbia',
  'University of Buenos Aires',
  'University of Calgary',
  'University of California, Berkeley',
  'University of California, Davis',
  'University of California, Irvine',
  'University of California, Los Angeles (UCLA)',
  'University of California, Merced',
  'University of California, Riverside',
  'University of California, San Diego',
  'University of California, Santa Barbara',
  'University of California, Santa Cruz',
  'University of Calcutta',
  'University of Cambridge',
  'University of Campinas',
  'University of Canterbury',
  'University of Cape Town',
  'University of Central Arkansas',
  'University of Central Florida',
  'University of Central Missouri',
  'University of Central Oklahoma',
  'University of Chicago',
  'University of Chile',
  'University of Cincinnati',
  'University of Coimbra',
  'University of Cologne',
  'University of Colorado Boulder',
  'University of Colorado Colorado Springs',
  'University of Colorado Denver',
  'University of Connecticut',
  'University of Copenhagen',
  'University of Dayton',
  'University of Delaware',
  'University of Denver',
  'University of Detroit Mercy',
  'University of Edinburgh',
  'University of Exeter',
  'University of Florence',
  'University of Florida',
  'University of Frankfurt',
  'University of Freiburg',
  'University of Geneva',
  'University of Georgia',
  'University of Glasgow',
  'University of Göttingen',
  'University of Groningen',
  'University of Hamburg',
  'University of Hartford',
  'University of Hawaii',
  'University of Helsinki',
  'University of Hong Kong',
  'University of Houston',
  'University of Idaho',
  'University of Illinois Chicago',
  'University of Illinois Springfield',
  'University of Illinois Urbana-Champaign',
  'University of Indianapolis',
  'University of Iowa',
  'University of Johannesburg',
  'University of Kansas',
  'University of Kentucky',
  'University of La Verne',
  'University of Lausanne',
  'University of Leeds',
  'University of Leicester',
  'University of Lisbon',
  'University of Liverpool',
  'University of Louisville',
  'University of Maine',
  'University of Maine at Augusta',
  'University of Maine at Farmington',
  'University of Maine at Fort Kent',
  'University of Maine at Machias',
  'University of Maine at Presque Isle',
  'University of Manchester',
  'University of Mary',
  'University of Mary Hardin-Baylor',
  'University of Mary Washington',
  'University of Manitoba',
  'University of Mannheim',
  'University of Maryland',
  'University of Maryland, Baltimore County',
  'University of Massachusetts Amherst',
  'University of Massachusetts Boston',
  'University of Massachusetts Dartmouth',
  'University of Massachusetts Lowell',
  'University of Melbourne',
  'University of Memphis',
  'University of Miami',
  'University of Michigan',
  'University of Milan',
  'University of Minnesota',
  'University of Mississippi',
  'University of Missouri',
  'University of Missouri-Kansas City',
  'University of Missouri-Rolla',
  'University of Missouri-St. Louis',
  'University of Mobile',
  'University of Montana',
  'University of Montevallo',
  'University of Montreal',
  'University of Mumbai',
  'University of Nairobi',
  'University of Naples',
  'University of Nebraska-Lincoln',
  'University of Nebraska-Omaha',
  'University of Nevada, Las Vegas',
  'University of Nevada, Reno',
  'University of New Hampshire',
  'University of New Mexico',
  'University of New Orleans',
  'University of New South Wales',
  'University of North Alabama',
  'University of North Carolina at Asheville',
  'University of North Carolina at Chapel Hill',
  'University of North Carolina at Charlotte',
  'University of North Carolina at Greensboro',
  'University of North Carolina at Pembroke',
  'University of North Carolina Wilmington',
  'University of North Dakota',
  'University of North Florida',
  'University of North Texas',
  'University of Northern Colorado',
  'University of Northern Iowa',
  'University of Notre Dame',
  'University of Nottingham',
  'University of Oklahoma',
  'University of Oregon',
  'University of Oslo',
  'University of Otago',
  'University of Ottawa',
  'University of Oxford',
  'University of Padua',
  'University of Paris',
  'University of Pennsylvania',
  'University of Pittsburgh',
  'University of Portland',
  'University of Porto',
  'University of Pretoria',
  'University of Puerto Rico',
  'University of Queensland',
  'University of Redlands',
  'University of Rhode Island',
  'University of Richmond',
  'University of Rochester',
  'University of San Diego',
  'University of San Francisco',
  'University of São Paulo',
  'University of Saskatchewan',
  'University of Science and Technology of China',
  'University of Scranton',
  'University of Sheffield',
  'University of South Alabama',
  'University of South Carolina',
  'University of South Dakota',
  'University of South Florida',
  'University of Southampton',
  'University of Southern California',
  'University of Southern Indiana',
  'University of Southern Maine',
  'University of Southern Mississippi',
  'University of St Andrews',
  'University of Sioux Falls',
  'University of St. Francis',
  'University of St. Thomas',
  'University of Stuttgart',
  'University of Sussex',
  'University of Sydney',
  'University of Tampa',
  'University of Technology Sydney',
  'University of Tennessee',
  'University of Tennessee at Chattanooga',
  'University of Texas at Arlington',
  'University of Texas at Austin',
  'University of Texas at Dallas',
  'University of Texas at El Paso',
  'University of Texas at San Antonio',
  'University of the Andes (Colombia)',
  'University of the Pacific',
  'University of the Witwatersrand',
  'University of Toledo',
  'University of Toronto',
  'University of Tübingen',
  'University of Tulsa',
  'University of Turin',
  'University of Utah',
  'University of Valencia',
  'University of Vermont',
  'University of Victoria',
  'University of Virginia',
  'University of Warwick',
  'University of Washington',
  'University of Waterloo',
  'University of West Florida',
  'University of West Georgia',
  'University of Western Australia',
  'University of Wisconsin-Eau Claire',
  'University of Wisconsin-Green Bay',
  'University of Wisconsin-La Crosse',
  'University of Wisconsin-Madison',
  'University of Wisconsin-Milwaukee',
  'University of Wisconsin-Oshkosh',
  'University of Wisconsin-Parkside',
  'University of Wisconsin-Platteville',
  'University of Wisconsin-River Falls',
  'University of Wisconsin-Stevens Point',
  'University of Wisconsin-Stout',
  'University of Wisconsin-Superior',
  'University of Wisconsin-Whitewater',
  'University of Wyoming',
  'University of York',
  'University of Zurich',
  'Uppsala University',
  'Utah State University',
  'Utrecht University',
  'Valparaiso University',
  'Vanderbilt University',
  'Victoria University of Wellington',
  'Villa Julie College',
  'Villa Maria College',
  'Villanova University',
  'Vincennes University',
  'Virginia Commonwealth University',
  'Virginia Intermont College',
  'Virginia Military Institute',
  'Virginia State University',
  'Virginia Tech',
  'Virginia Union University',
  'Virginia Wesleyan College',
  'Viterbo University',
  'Voorhees College',
  'Wageningen University',
  'Wake Forest University',
  'Waseda University',
  'Washington State University',
  'Washington University in St. Louis',
  'Wayne State University',
  'Weizmann Institute of Science',
  'Wellesley College',
  'Wells College',
  'Wentworth Institute of Technology',
  'Wesleyan College',
  'Wesleyan University',
  'Wesley College',
  'West Chester University',
  'West Liberty University',
  'West Texas A&M University',
  'West Virginia State University',
  'West Virginia University',
  'West Virginia University Institute of Technology',
  'West Virginia Wesleyan College',
  'Westchester University',
  'Western Carolina University',
  'Western Connecticut State University',
  'Western Governors University',
  'Western Illinois University',
  'Western Kentucky University',
  'Western Michigan University',
  'Western New England University',
  'Western New Mexico University',
  'Western Oregon University',
  'Western State Colorado University',
  'Western University',
  'Western Washington University',
  'Westfield State University',
  'Westminster College',
  'Westmont College',
  'Wheaton College',
  'Wheeling Jesuit University',
  'Wheelock College',
  'Whitman College',
  'Whittier College',
  'Whitworth University',
  'Wichita State University',
  'Widener University',
  'Wilberforce University',
  'Wiley College',
  'Wilkes University',
  'Willamette University',
  'William Carey University',
  'William Jewell College',
  'William Jessup University',
  'William Paterson University',
  'William Peace University',
  'William Penn University',
  'William Woods University',
  'Williams Baptist College',
  'Williams College',
  'Wilmington College',
  'Wilmington University',
  'Wilson College',
  'Wingate University',
  'Winona State University',
  'Winston-Salem State University',
  'Winthrop University',
  'Wisconsin Lutheran College',
  'Wittenberg University',
  'Wofford College',
  'Woodbury University',
  'Worcester Polytechnic Institute',
  'Worcester State University',
  'Wright State University',
  'Wuhan University',
  'Xi\'an Jiaotong University',
  'Yale University',
  'Yeshiva University',
  'Yonsei University',
  'York College',
  'York College of Pennsylvania',
  'York University',
  'Young Harris College',
  'Youngstown State University',
  'Zhejiang University',
  'Other'
].sort();

export function DegreeSelect({ value, onChange, placeholder = "Select degree" }) {
  return (
    <>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger>
          <SelectValue placeholder={placeholder} />
        </SelectTrigger>
        <SelectContent>
          {DEGREES.map(degree => (
            <SelectItem key={degree} value={degree}>{degree}</SelectItem>
          ))}
        </SelectContent>
      </Select>
      <Input
        value={value || ''}
        onChange={(e) => onChange(e.target.value)}
        placeholder="Or type your own degree"
        className="mt-2"
      />
    </>
  );
}

export function MajorSelect({ value, onChange, placeholder = "Select major" }) {
  return (
    <>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger>
          <SelectValue placeholder={placeholder} />
        </SelectTrigger>
        <SelectContent>
          {MAJORS.map(major => (
            <SelectItem key={major} value={major}>{major}</SelectItem>
          ))}
        </SelectContent>
      </Select>
      <Input
        value={value || ''}
        onChange={(e) => onChange(e.target.value)}
        placeholder="Or type your own major"
        className="mt-2"
      />
    </>
  );
}

export function UniversitySelect({ value, onChange, placeholder = "Select university" }) {
  return (
    <>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger>
          <SelectValue placeholder={placeholder} />
        </SelectTrigger>
        <SelectContent className="max-h-[300px]">
          {UNIVERSITIES.map(university => (
            <SelectItem key={university} value={university}>{university}</SelectItem>
          ))}
        </SelectContent>
      </Select>
      <Input
        value={value || ''}
        onChange={(e) => onChange(e.target.value)}
        placeholder="Or type your own university"
        className="mt-2"
      />
    </>
  );
}