import React from 'react';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Input } from '@/components/ui/input';

const DEGREES = [
  'High School Diploma',
  'Associate Degree',
  'Bachelor of Arts (BA)',
  'Bachelor of Science (BS)',
  'Bachelor of Business Administration (BBA)',
  'Bachelor of Engineering (BE)',
  'Bachelor of Technology (BTech)',
  'Master of Arts (MA)',
  'Master of Science (MS)',
  'Master of Business Administration (MBA)',
  'Master of Engineering (ME)',
  'Master of Technology (MTech)',
  'Doctor of Philosophy (PhD)',
  'Juris Doctor (JD)',
  'Doctor of Medicine (MD)',
  'Doctor of Education (EdD)',
  'Certificate',
  'Diploma',
  'Other'
];

const MAJORS = [
  'Computer Science',
  'Information Technology',
  'Software Engineering',
  'Data Science',
  'Artificial Intelligence',
  'Business Administration',
  'Finance',
  'Accounting',
  'Marketing',
  'Economics',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Psychology',
  'Sociology',
  'Political Science',
  'English',
  'Communications',
  'Nursing',
  'Biology',
  'Chemistry',
  'Physics',
  'Mathematics',
  'Statistics',
  'Graphic Design',
  'Fine Arts',
  'Education',
  'Law',
  'Medicine',
  'Other'
];

const UNIVERSITIES = [
  'Aalto University',
  'Aarhus University',
  'Adelphi University',
  'Air Force Institute of Technology',
  'Aix-Marseille University',
  'Alabama A&M University',
  'Alabama State University',
  'Alaska Pacific University',
  'Albany State University',
  'Alcorn State University',
  'American University',
  'American University in Cairo',
  'American University of Beirut',
  'Amherst College',
  'Anna University',
  'Appalachian State University',
  'Arizona State University',
  'Arkansas State University',
  'Arkansas Tech University',
  'Auburn University',
  'Augsburg University',
  'Augusta University',
  'Austin Peay State University',
  'Australian National University',
  'Autonomous University of Madrid',
  'Ball State University',
  'Banaras Hindu University',
  'Baylor University',
  'Beihang University',
  'Belmont University',
  'Bentley University',
  'Binghamton University',
  'Birla Institute of Technology and Science (BITS Pilani)',
  'Boise State University',
  'Boston College',
  'Boston University',
  'Bowling Green State University',
  'Brandeis University',
  'Brigham Young University',
  'Brown University',
  'Butler University',
  'Cairo University',
  'California Institute of Technology (Caltech)',
  'California Polytechnic State University',
  'California State University, Chico',
  'California State University, Fresno',
  'California State University, Fullerton',
  'California State University, Long Beach',
  'California State University, Los Angeles',
  'California State University, Northridge',
  'California State University, Sacramento',
  'Carleton University',
  'Carnegie Mellon University',
  'Case Western Reserve University',
  'Central Connecticut State University',
  'Central Michigan University',
  'Central Washington University',
  'Chalmers University of Technology',
  'Chapman University',
  'Chinese University of Hong Kong',
  'City University of Hong Kong',
  'Claremont McKenna College',
  'Clark University',
  'Clemson University',
  'Cleveland State University',
  'College of William & Mary',
  'Colorado School of Mines',
  'Colorado State University',
  'Columbia University',
  'Complutense University of Madrid',
  'Cornell University',
  'Creighton University',
  'Dalhousie University',
  'Dartmouth College',
  'Delft University of Technology',
  'Delhi University',
  'DePaul University',
  'Drexel University',
  'Duke University',
  'Durham University',
  'East Carolina University',
  'East Tennessee State University',
  'Eastern Illinois University',
  'Eastern Kentucky University',
  'Eastern Michigan University',
  'Eastern Washington University',
  'École Normale Supérieure',
  'École Polytechnique',
  'Eindhoven University of Technology',
  'Emory University',
  'EPFL (École Polytechnique Fédérale de Lausanne)',
  'Erasmus University Rotterdam',
  'ETH Zurich',
  'Fairfield University',
  'Federal University of Rio de Janeiro',
  'Florida Atlantic University',
  'Florida Gulf Coast University',
  'Florida International University',
  'Florida State University',
  'Fordham University',
  'Free University of Berlin',
  'Fudan University',
  'George Mason University',
  'George Washington University',
  'Georgetown University',
  'Georgia Institute of Technology',
  'Georgia Southern University',
  'Georgia State University',
  'Ghent University',
  'Gonzaga University',
  'Grand Valley State University',
  'Grenoble Alpes University',
  'Hampton University',
  'Hanyang University',
  'Harbin Institute of Technology',
  'Harvard University',
  'Harvey Mudd College',
  'Hawaii Pacific University',
  'HEC Paris',
  'Hebrew University of Jerusalem',
  'Heidelberg University',
  'Hokkaido University',
  'Hong Kong Polytechnic University',
  'Hong Kong University of Science and Technology',
  'Howard University',
  'Humboldt University of Berlin',
  'IE Business School',
  'Illinois Institute of Technology',
  'Illinois State University',
  'Imperial College London',
  'Indiana State University',
  'Indiana University Bloomington',
  'Indiana University of Pennsylvania',
  'Indiana University-Purdue University Indianapolis',
  'INSEAD',
  'Iowa State University',
  'Jadavpur University',
  'James Madison University',
  'Jawaharlal Nehru University',
  'Johns Hopkins University',
  'KAIST',
  'Kansas State University',
  'Karlsruhe Institute of Technology',
  'Keio University',
  'Kennesaw State University',
  'Kent State University',
  'King Abdullah University of Science and Technology',
  'King\'s College London',
  'Korea University',
  'KU Leuven',
  'Kyoto University',
  'Kyushu University',
  'Lancaster University',
  'Lehigh University',
  'Leiden University',
  'Liberty University',
  'London School of Economics (LSE)',
  'Long Island University',
  'Louisiana State University',
  'Louisiana Tech University',
  'Loughborough University',
  'Loyola Marymount University',
  'Loyola University Chicago',
  'Ludwig Maximilian University of Munich',
  'Lund University',
  'Macquarie University',
  'Marquette University',
  'Marshall University',
  'Massachusetts Institute of Technology (MIT)',
  'McGill University',
  'McMaster University',
  'Miami University',
  'Michigan State University',
  'Middle Tennessee State University',
  'Mississippi State University',
  'Monash University',
  'Montana State University',
  'Monterrey Institute of Technology',
  'Morehead State University',
  'Morgan State University',
  'Murray State University',
  'Nagoya University',
  'Nanjing University',
  'Nankai University',
  'Nanyang Technological University',
  'National Autonomous University of Mexico',
  'National University of Singapore',
  'Naval Postgraduate School',
  'New Jersey Institute of Technology',
  'New Mexico State University',
  'New York University (NYU)',
  'Newcastle University',
  'Nicholls State University',
  'North Carolina A&T State University',
  'North Carolina State University',
  'North Dakota State University',
  'Northeastern University',
  'Northern Arizona University',
  'Northern Illinois University',
  'Northern Kentucky University',
  'Northwestern University',
  'Norwich University',
  'Oakland University',
  'Oberlin College',
  'Ohio State University',
  'Ohio University',
  'Oklahoma State University',
  'Old Dominion University',
  'Oregon State University',
  'Osaka University',
  'Pace University',
  'Pacific Lutheran University',
  'Penn State University',
  'Pepperdine University',
  'Politecnico di Milano',
  'Polytechnic University of Puerto Rico',
  'Pompeu Fabra University',
  'Pontifical Catholic University of Chile',
  'Portland State University',
  'POSTECH',
  'Princeton University',
  'Purdue University',
  'Qatar University',
  'Queen Mary University of London',
  'Queen\'s University',
  'Queensland University of Technology',
  'Quinnipiac University',
  'Radford University',
  'Rensselaer Polytechnic Institute',
  'Rice University',
  'RMIT University',
  'Rochester Institute of Technology',
  'Rowan University',
  'Royal Institute of Technology (KTH)',
  'Rutgers University',
  'RWTH Aachen University',
  'Sacred Heart University',
  'Saginaw Valley State University',
  'Sam Houston State University',
  'San Diego State University',
  'San Francisco State University',
  'San Jose State University',
  'Santa Clara University',
  'Sapienza University of Rome',
  'Sciences Po',
  'Seattle Pacific University',
  'Seattle University',
  'Seoul National University',
  'Seton Hall University',
  'Shanghai Jiao Tong University',
  'Sichuan University',
  'Simon Fraser University',
  'Singapore Management University',
  'Sorbonne University',
  'South Dakota State University',
  'Southeast Missouri State University',
  'Southeastern Louisiana University',
  'Southern Illinois University Carbondale',
  'Southern Methodist University',
  'Southern New Hampshire University',
  'Southern Utah University',
  'St. John\'s University',
  'Stanford University',
  'Stellenbosch University',
  'Stephen F. Austin State University',
  'Stetson University',
  'Stevens Institute of Technology',
  'Stockholm University',
  'Stony Brook University',
  'Suffolk University',
  'Sun Yat-sen University',
  'Sungkyunkwan University',
  'SUNY Albany',
  'SUNY Buffalo',
  'Swarthmore College',
  'Syracuse University',
  'Technical University of Denmark',
  'Technical University of Munich',
  'Technion - Israel Institute of Technology',
  'Tel Aviv University',
  'Temple University',
  'Tennessee State University',
  'Tennessee Tech University',
  'Texas A&M University',
  'Texas Christian University',
  'Texas Southern University',
  'Texas State University',
  'Texas Tech University',
  'The Citadel',
  'The New School',
  'Tianjin University',
  'Tohoku University',
  'Tokyo Institute of Technology',
  'Towson University',
  'Tsinghua University',
  'TU Berlin',
  'TU Dresden',
  'Tufts University',
  'Tulane University',
  'United Arab Emirates University',
  'Université Libre de Bruxelles',
  'Université Paris-Saclay',
  'University College London (UCL)',
  'University of Aberdeen',
  'University of Adelaide',
  'University of Akron',
  'University of Alabama',
  'University of Alabama at Birmingham',
  'University of Alabama in Huntsville',
  'University of Alaska Anchorage',
  'University of Alaska Fairbanks',
  'University of Alberta',
  'University of Amsterdam',
  'University of Antwerp',
  'University of Arizona',
  'University of Arkansas',
  'University of Auckland',
  'University of Baltimore',
  'University of Barcelona',
  'University of Basel',
  'University of Bath',
  'University of Bergen',
  'University of Bern',
  'University of Birmingham',
  'University of Bologna',
  'University of Bonn',
  'University of Bristol',
  'University of British Columbia',
  'University of Buenos Aires',
  'University of Calgary',
  'University of California, Berkeley',
  'University of California, Davis',
  'University of California, Irvine',
  'University of California, Los Angeles (UCLA)',
  'University of California, Merced',
  'University of California, Riverside',
  'University of California, San Diego',
  'University of California, Santa Barbara',
  'University of California, Santa Cruz',
  'University of Calcutta',
  'University of Cambridge',
  'University of Campinas',
  'University of Canterbury',
  'University of Cape Town',
  'University of Central Arkansas',
  'University of Central Florida',
  'University of Central Missouri',
  'University of Central Oklahoma',
  'University of Chicago',
  'University of Chile',
  'University of Cincinnati',
  'University of Coimbra',
  'University of Cologne',
  'University of Colorado Boulder',
  'University of Colorado Colorado Springs',
  'University of Colorado Denver',
  'University of Connecticut',
  'University of Copenhagen',
  'University of Dayton',
  'University of Delaware',
  'University of Denver',
  'University of Detroit Mercy',
  'University of Edinburgh',
  'University of Exeter',
  'University of Florence',
  'University of Florida',
  'University of Frankfurt',
  'University of Freiburg',
  'University of Geneva',
  'University of Georgia',
  'University of Glasgow',
  'University of Göttingen',
  'University of Groningen',
  'University of Hamburg',
  'University of Hartford',
  'University of Hawaii',
  'University of Helsinki',
  'University of Hong Kong',
  'University of Houston',
  'University of Idaho',
  'University of Illinois Chicago',
  'University of Illinois Springfield',
  'University of Illinois Urbana-Champaign',
  'University of Indianapolis',
  'University of Iowa',
  'University of Johannesburg',
  'University of Kansas',
  'University of Kentucky',
  'University of La Verne',
  'University of Lausanne',
  'University of Leeds',
  'University of Leicester',
  'University of Lisbon',
  'University of Liverpool',
  'University of Louisville',
  'University of Maine',
  'University of Manchester',
  'University of Manitoba',
  'University of Mannheim',
  'University of Maryland',
  'University of Maryland, Baltimore County',
  'University of Massachusetts Amherst',
  'University of Massachusetts Boston',
  'University of Massachusetts Lowell',
  'University of Melbourne',
  'University of Memphis',
  'University of Miami',
  'University of Michigan',
  'University of Milan',
  'University of Minnesota',
  'University of Mississippi',
  'University of Missouri',
  'University of Missouri-Kansas City',
  'University of Missouri-St. Louis',
  'University of Montana',
  'University of Montevallo',
  'University of Montreal',
  'University of Mumbai',
  'University of Nairobi',
  'University of Naples',
  'University of Nebraska-Lincoln',
  'University of Nebraska-Omaha',
  'University of Nevada, Las Vegas',
  'University of Nevada, Reno',
  'University of New Hampshire',
  'University of New Mexico',
  'University of New Orleans',
  'University of New South Wales',
  'University of North Alabama',
  'University of North Carolina at Chapel Hill',
  'University of North Carolina at Charlotte',
  'University of North Carolina at Greensboro',
  'University of North Carolina Wilmington',
  'University of North Dakota',
  'University of North Florida',
  'University of North Texas',
  'University of Northern Colorado',
  'University of Northern Iowa',
  'University of Notre Dame',
  'University of Nottingham',
  'University of Oklahoma',
  'University of Oregon',
  'University of Oslo',
  'University of Otago',
  'University of Ottawa',
  'University of Oxford',
  'University of Padua',
  'University of Paris',
  'University of Pennsylvania',
  'University of Pittsburgh',
  'University of Portland',
  'University of Porto',
  'University of Pretoria',
  'University of Puerto Rico',
  'University of Queensland',
  'University of Redlands',
  'University of Rhode Island',
  'University of Richmond',
  'University of Rochester',
  'University of San Diego',
  'University of San Francisco',
  'University of São Paulo',
  'University of Saskatchewan',
  'University of Science and Technology of China',
  'University of Scranton',
  'University of Sheffield',
  'University of South Alabama',
  'University of South Carolina',
  'University of South Dakota',
  'University of South Florida',
  'University of Southampton',
  'University of Southern California',
  'University of Southern Indiana',
  'University of Southern Maine',
  'University of Southern Mississippi',
  'University of St Andrews',
  'University of St. Thomas',
  'University of Stuttgart',
  'University of Sussex',
  'University of Sydney',
  'University of Tampa',
  'University of Technology Sydney',
  'University of Tennessee',
  'University of Tennessee at Chattanooga',
  'University of Texas at Arlington',
  'University of Texas at Austin',
  'University of Texas at Dallas',
  'University of Texas at El Paso',
  'University of Texas at San Antonio',
  'University of the Andes (Colombia)',
  'University of the Pacific',
  'University of the Witwatersrand',
  'University of Toledo',
  'University of Toronto',
  'University of Tübingen',
  'University of Tulsa',
  'University of Turin',
  'University of Utah',
  'University of Valencia',
  'University of Vermont',
  'University of Victoria',
  'University of Virginia',
  'University of Warwick',
  'University of Washington',
  'University of Waterloo',
  'University of West Florida',
  'University of West Georgia',
  'University of Western Australia',
  'University of Wisconsin-Madison',
  'University of Wisconsin-Milwaukee',
  'University of Wyoming',
  'University of York',
  'University of Zurich',
  'Uppsala University',
  'Utah State University',
  'Utrecht University',
  'Valparaiso University',
  'Vanderbilt University',
  'Victoria University of Wellington',
  'Villanova University',
  'Virginia Commonwealth University',
  'Virginia Tech',
  'Wageningen University',
  'Wake Forest University',
  'Waseda University',
  'Washington State University',
  'Washington University in St. Louis',
  'Wayne State University',
  'Weizmann Institute of Science',
  'West Chester University',
  'West Virginia University',
  'Western Carolina University',
  'Western Illinois University',
  'Western Kentucky University',
  'Western Michigan University',
  'Western University',
  'Western Washington University',
  'Wichita State University',
  'Widener University',
  'William Paterson University',
  'Wright State University',
  'Wuhan University',
  'Xi\'an Jiaotong University',
  'Yale University',
  'Yonsei University',
  'York University',
  'Youngstown State University',
  'Zhejiang University',
  'Other'
].sort();

export function DegreeSelect({ value, onChange, placeholder = "Select degree" }) {
  return (
    <>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger>
          <SelectValue placeholder={placeholder} />
        </SelectTrigger>
        <SelectContent>
          {DEGREES.map(degree => (
            <SelectItem key={degree} value={degree}>{degree}</SelectItem>
          ))}
        </SelectContent>
      </Select>
      <Input
        value={value || ''}
        onChange={(e) => onChange(e.target.value)}
        placeholder="Or type your own degree"
        className="mt-2"
      />
    </>
  );
}

export function MajorSelect({ value, onChange, placeholder = "Select major" }) {
  return (
    <>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger>
          <SelectValue placeholder={placeholder} />
        </SelectTrigger>
        <SelectContent>
          {MAJORS.map(major => (
            <SelectItem key={major} value={major}>{major}</SelectItem>
          ))}
        </SelectContent>
      </Select>
      <Input
        value={value || ''}
        onChange={(e) => onChange(e.target.value)}
        placeholder="Or type your own major"
        className="mt-2"
      />
    </>
  );
}

export function UniversitySelect({ value, onChange, placeholder = "Select university" }) {
  return (
    <>
      <Select value={value} onValueChange={onChange}>
        <SelectTrigger>
          <SelectValue placeholder={placeholder} />
        </SelectTrigger>
        <SelectContent className="max-h-[300px]">
          {UNIVERSITIES.map(university => (
            <SelectItem key={university} value={university}>{university}</SelectItem>
          ))}
        </SelectContent>
      </Select>
      <Input
        value={value || ''}
        onChange={(e) => onChange(e.target.value)}
        placeholder="Or type your own university"
        className="mt-2"
      />
    </>
  );
}